/**
 * (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.
 */
export default (initInfo) => {
  const { settings } = initInfo;
  const {
    isTestEvent = false,
    testEventCode = '',
    eventName = '',
    eventTime = '',
    eventSourceUrl = '',
    optOut = '',
    eventId = '',
    actionSource = '',
    email = '',
    phone = '',
    gender = '',
    dob = '',
    lastName = '',
    firstName = '',
    city = '',
    state = '',
    zip = '',
    country = '',
    externalId = '',
    clientIpAddress = '',
    clientUserAgent = '',
    fbc = '',
    fbp = '',
    subscriptionId = '',
    fbLoginId = '',
    leadId = '',
    value = '',
    currency = '',
    contentName = '',
    contentCategory = '',
    contentIds = '',
    contents = '',
    contentType = '',
    orderId = '',
    predictedLtv = '',
    numItems = '',
    searchString = '',
    status = '',
    deliveryCategory = '',
    lduEnabled = true,
    customData = ''
  } = settings || {};
  return {
    isTestEvent,
    testEventCode,
    eventName,
    eventTime,
    eventSourceUrl,
    optOut,
    eventId,
    actionSource,
    email,
    phone,
    gender,
    dob,
    lastName,
    firstName,
    city,
    state,
    zip,
    country,
    externalId,
    clientIpAddress,
    clientUserAgent,
    fbc,
    fbp,
    subscriptionId,
    fbLoginId,
    leadId,
    value,
    currency,
    contentName,
    contentCategory,
    contentIds,
    contents,
    contentType,
    orderId,
    predictedLtv,
    numItems,
    searchString,
    status,
    deliveryCategory,
    lduEnabled,
    customData
  };
};
